// Writes the client's copy of every value and limit the API validates, from the committed
// OpenAPI document. Run by `just contract`; the drift check in CI fails when the output is stale.
//
// Usage: generate-vocabulary <api/openapi.json> <Vocabulary.swift>

import Foundation

struct GenerationError: Error, CustomStringConvertible {
    let description: String
}

/// Enum schema name to the array's Swift name, in the order they are emitted. A schema
/// missing here fails the run, so a new list gets a deliberate client name rather than an
/// invented one.
let arrayNames: [(schema: String, swift: String)] = [
    ("AudioQuality", "audioQualities"),
    ("Instrument", "instruments"),
    ("Mode", "modes"),
    ("Provider", "providers"),
    ("RecordingSource", "recordingSources"),
    ("RecordingState", "recordingStates"),
    ("TimeSignature", "timeSignatures"),
    ("TuneStatus", "statuses"),
]

/// A limits namespace to the row schemas it gathers string and array limits from, in the
/// order they are emitted. A tune and its user row are one form to the client, so their
/// limits are one namespace. A row missing here fails the run, so a renamed schema cannot
/// silently empty a namespace.
let limitNamespaces: [(name: String, rows: [String])] = [
    ("Tune", ["TuneRow", "UserTuneRow", "InstrumentTuning"]),
    ("List", ["ListRow"]),
    ("Link", ["RecordingLinkRow"]),
    ("Recording", ["RecordingRow"]),
]

func camelCase(_ snakeCase: String) -> String {
    let parts = snakeCase.split(separator: "_")
    guard let first = parts.first else { return snakeCase }
    let rest = parts.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }
    return ([String(first)] + rest).joined()
}

/// A string property's max length, directly, under `anyOf`, or on its array items; else an
/// array property's max items.
func limit(of property: [String: Any]) -> Int? {
    let anyOf = (property["anyOf"] as? [[String: Any]]) ?? []
    let items = (property["items"] as? [String: Any]).map { [$0] } ?? []
    for candidate in [property] + anyOf + items {
        if candidate["type"] as? String == "string", let maxLength = candidate["maxLength"] as? Int {
            return maxLength
        }
    }
    for candidate in [property] + anyOf {
        if candidate["type"] as? String == "array", let maxItems = candidate["maxItems"] as? Int {
            return maxItems
        }
    }
    return nil
}

func quote(_ value: String) -> String {
    "\"\(value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\""))\""
}

func render(_ document: [String: Any]) throws -> String {
    guard let components = document["components"] as? [String: Any],
        let schemas = components["schemas"] as? [String: Any]
    else {
        throw GenerationError(description: "no components.schemas in the document")
    }

    var lines = [
        "// Generated by Tools/Sources/generate-vocabulary from api/openapi.json. Do not edit.",
        "// The API is the source of every value and limit here; see api/src/crosstune/vocabulary.py.",
        "",
        "public enum Vocabulary {",
    ]

    for (schemaName, swiftName) in arrayNames {
        guard let schema = schemas[schemaName] as? [String: Any],
            schema["type"] as? String == "string",
            let enumValues = schema["enum"] as? [String]
        else {
            throw GenerationError(description: "no string enum schema named \(schemaName); update arrayNames")
        }
        let values = enumValues.map(quote).joined(separator: ", ")
        lines.append("    public static let \(swiftName): [String] = [\(values)]")
    }

    lines.append("")
    lines.append("    public enum Limits {")
    for (namespaceName, rows) in limitNamespaces {
        var fields: [(name: String, limit: Int)] = []
        for row in rows {
            guard let schema = schemas[row] as? [String: Any],
                let properties = schema["properties"] as? [String: Any]
            else {
                throw GenerationError(description: "no row schema named \(row); update limitNamespaces")
            }
            for (field, property) in properties {
                guard let property = property as? [String: Any], let value = limit(of: property) else { continue }
                fields.append((camelCase(field), value))
            }
        }
        lines.append("        public enum \(namespaceName) {")
        // Dictionary key order from JSONSerialization is unspecified, so fields are sorted
        // here to make a fresh run byte-identical every time.
        for (name, value) in fields.sorted(by: { $0.name < $1.name }) {
            lines.append("            public static let \(name) = \(value)")
        }
        lines.append("        }")
    }
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return lines.joined(separator: "\n")
}

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
    FileHandle.standardError.write(Data("usage: generate-vocabulary <input.json> <output.swift>\n".utf8))
    exit(64)
}

do {
    let input = try Data(contentsOf: URL(fileURLWithPath: arguments[1]))
    guard let document = try JSONSerialization.jsonObject(with: input) as? [String: Any] else {
        throw GenerationError(description: "\(arguments[1]) is not a JSON object")
    }
    try render(document).write(to: URL(fileURLWithPath: arguments[2]), atomically: true, encoding: .utf8)
} catch {
    // A top-level throw traps with a crash report; a contract problem is the reader's to fix.
    let message = (error as? GenerationError)?.description ?? error.localizedDescription
    FileHandle.standardError.write(Data("generate-vocabulary: \(message)\n".utf8))
    exit(1)
}
