[default]
    locale = "en-us"

[files]
    extend-exclude = [".cache", ".venv", "node_modules", "*.lock", "web/src/api/openapi.json", "pnpm-lock.yaml", "web/src/api/schema.d.ts", "web/src/routeTree.gen.ts", "web/dist", "web/dev-dist"]
