/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/links/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve
         * @description Provider, canonical URL, title, and artwork for a pasted link.
         */
        post: operations["resolve_v1_links_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The calling user's profile.
         */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull
         * @description Every one of the caller's rows changed after `since`, oldest first.
         */
        get: operations["pull_v1_sync_pull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push
         * @description Apply a batch of client changes. One result per change, in order.
         */
        post: operations["push_v1_sync_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Change
         * @description One client change. updated_at is the client's clock and decides last-write-wins.
         */
        Change: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Op
             * @enum {string}
             */
            op: "upsert" | "delete";
            /**
             * Table
             * @enum {string}
             */
            table: "songs" | "user_songs" | "lists" | "list_items" | "recording_links" | "user_settings";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ListChangeResult
         * @description The outcome of one change to a list.
         */
        ListChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["ListRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "lists";
        };
        /**
         * ListItemChangeResult
         * @description The outcome of one change to a list item.
         */
        ListItemChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["ListItemRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "list_items";
        };
        /**
         * ListItemPullRow
         * @description A list item row in a pull page.
         */
        ListItemPullRow: {
            row: components["schemas"]["ListItemRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "list_items";
        };
        /**
         * ListItemRow
         * @description A stored list item, as push and pull return it. Ownership comes from its list.
         */
        ListItemRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * List Id
             * Format: uuid
             */
            list_id: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Server Seq */
            server_seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Song Id
             * Format: uuid
             */
            user_song_id: string;
        };
        /**
         * ListPullRow
         * @description A list row in a pull page.
         */
        ListPullRow: {
            row: components["schemas"]["ListRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "lists";
        };
        /**
         * ListRow
         * @description A stored list, as push and pull return it.
         */
        ListRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Server Seq */
            server_seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * MeResponse
         * @description The calling user's public profile.
         */
        MeResponse: {
            /** Clerk User Id */
            clerk_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * Problem
         * @description An RFC 9457 problem details body, the shape of every error this API returns.
         */
        Problem: {
            /** Detail */
            detail: string;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * PullResponse
         * @description A page of rows changed since the given cursor.
         */
        PullResponse: {
            /** Has More */
            has_more: boolean;
            /** Next Since */
            next_since: number;
            /** Rows */
            rows: (components["schemas"]["SongPullRow"] | components["schemas"]["UserSongPullRow"] | components["schemas"]["ListPullRow"] | components["schemas"]["ListItemPullRow"] | components["schemas"]["RecordingLinkPullRow"] | components["schemas"]["UserSettingsPullRow"])[];
        };
        /**
         * PushRequest
         * @description A batch of client changes to apply.
         */
        PushRequest: {
            /** Changes */
            changes: components["schemas"]["Change"][];
        };
        /**
         * PushResponse
         * @description One result per change, same order as the request.
         */
        PushResponse: {
            /** Results */
            results: (components["schemas"]["SongChangeResult"] | components["schemas"]["UserSongChangeResult"] | components["schemas"]["ListChangeResult"] | components["schemas"]["ListItemChangeResult"] | components["schemas"]["RecordingLinkChangeResult"] | components["schemas"]["UserSettingsChangeResult"])[];
        };
        /**
         * RecordingLinkChangeResult
         * @description The outcome of one change to a recording link.
         */
        RecordingLinkChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["RecordingLinkRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "recording_links";
        };
        /**
         * RecordingLinkPullRow
         * @description A recording link row in a pull page.
         */
        RecordingLinkPullRow: {
            row: components["schemas"]["RecordingLinkRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "recording_links";
        };
        /**
         * RecordingLinkRow
         * @description A stored recording link, as push and pull return it.
         */
        RecordingLinkRow: {
            /**
             * Added By User Id
             * Format: uuid
             */
            added_by_user_id: string;
            /** Artwork Url */
            artwork_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label?: string | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Provider */
            provider: string;
            /** Provider Ref */
            provider_ref?: string | null;
            /** Server Seq */
            server_seq: number;
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Title */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * ResolveRequest
         * @description Body of a resolve request: the URL the user just pasted.
         */
        ResolveRequest: {
            /** Url */
            url: string;
        };
        /**
         * ResolveResponse
         * @description Provider, canonical URL, title, and artwork for a resolved link.
         */
        ResolveResponse: {
            /** Artwork Url */
            artwork_url: string | null;
            /** Provider */
            provider: string;
            /** Provider Ref */
            provider_ref: string | null;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /**
         * SongChangeResult
         * @description The outcome of one change to a song.
         */
        SongChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["SongRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "songs";
        };
        /**
         * SongPullRow
         * @description A song row in a pull page.
         */
        SongPullRow: {
            row: components["schemas"]["SongRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "songs";
        };
        /**
         * SongRow
         * @description A stored song, as push and pull return it.
         */
        SongRow: {
            /**
             * Alternate Titles
             * @default []
             */
            alternate_titles: string[];
            /** Banjo Tuning */
            banjo_tuning?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Feel */
            feel?: string | null;
            /** Genre */
            genre?: string | null;
            /** Has Lyrics */
            has_lyrics?: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Crooked
             * @default false
             */
            is_crooked: boolean;
            /** Key */
            key?: string | null;
            /** Mode */
            mode?: string | null;
            /** Owner User Id */
            owner_user_id: string | null;
            /** Part Structure */
            part_structure?: string | null;
            /** Server Seq */
            server_seq: number;
            /** Time Signature */
            time_signature?: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Violin Tuning */
            violin_tuning?: string | null;
        };
        /**
         * UserSettingsChangeResult
         * @description The outcome of one change to a user's settings.
         */
        UserSettingsChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["UserSettingsRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_settings";
        };
        /**
         * UserSettingsPullRow
         * @description A settings row in a pull page.
         */
        UserSettingsPullRow: {
            row: components["schemas"]["UserSettingsRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_settings";
        };
        /**
         * UserSettingsRow
         * @description A stored settings row, as push and pull return it.
         */
        UserSettingsRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instruments
             * @default []
             */
            instruments: string[];
            /** Server Seq */
            server_seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * UserSongChangeResult
         * @description The outcome of one change to a user song.
         */
        UserSongChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["UserSongRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_songs";
        };
        /**
         * UserSongPullRow
         * @description A user song row in a pull page.
         */
        UserSongPullRow: {
            row: components["schemas"]["UserSongRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_songs";
        };
        /**
         * UserSongRow
         * @description A stored user song, as push and pull return it.
         */
        UserSongRow: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Learned From */
            learned_from?: string | null;
            /** Learned On */
            learned_on?: string | null;
            /** Notes */
            notes?: string | null;
            /** Server Seq */
            server_seq: number;
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_v1_links_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    pull_v1_sync_pull_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    push_v1_sync_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
