/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/links/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve
         * @description Provider, canonical URL, title, and artwork for a pasted link.
         */
        post: operations["resolve_v1_links_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The calling user's profile and storage figures.
         */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description A presigned GET for the playback file of a ready recording.
         */
        get: operations["download_v1_recordings__recording_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry
         * @description Transcode the object already in the bucket again, for a recording that failed.
         *
         *     A recording whose uploaded object is gone is uploaded again through a new
         *     slot instead; this route only re-runs the transcode.
         */
        post: operations["retry_v1_recordings__recording_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}/upload-slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Slot
         * @description A presigned PUT for one recording's file, once the quota allows it.
         *
         *     A failed recording is issued a slot too, and returns to pending_upload: it is
         *     the only way back for one whose uploaded object is no longer in the bucket.
         */
        post: operations["upload_slot_v1_recordings__recording_id__upload_slot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}/uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Finished
         * @description Confirm the object landed and queue its transcode. Repeating the call changes nothing.
         */
        post: operations["upload_finished_v1_recordings__recording_id__uploaded_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull
         * @description Every one of the caller's rows changed after `since`, oldest first.
         */
        get: operations["pull_v1_sync_pull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push
         * @description Apply a batch of client changes. One result per change, in order.
         */
        post: operations["push_v1_sync_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioQuality
         * @description A capture bitrate preset.
         * @enum {string}
         */
        AudioQuality: "low" | "standard" | "high";
        /**
         * Change
         * @description One client change. updated_at is the client's clock and decides last-write-wins.
         */
        Change: {
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Op
             * @enum {string}
             */
            op: "upsert" | "delete";
            /**
             * Table
             * @enum {string}
             */
            table: "songs" | "user_songs" | "lists" | "list_items" | "recording_links" | "recordings" | "user_settings";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Instrument
         * @description An instrument a player can say they play.
         * @enum {string}
         */
        Instrument: "violin" | "banjo";
        /**
         * ListChangeResult
         * @description The outcome of one change to a list.
         */
        ListChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["ListRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "lists";
        };
        /**
         * ListItemChangeResult
         * @description The outcome of one change to a list item.
         */
        ListItemChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["ListItemRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "list_items";
        };
        /**
         * ListItemPullRow
         * @description A list item row in a pull page.
         */
        ListItemPullRow: {
            row: components["schemas"]["ListItemRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "list_items";
        };
        /**
         * ListItemRow
         * @description A stored list item, as push and pull return it. Ownership comes from its list.
         */
        ListItemRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * List Id
             * Format: uuid
             */
            list_id: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Server Seq */
            server_seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Song Id
             * Format: uuid
             */
            user_song_id: string;
        };
        /**
         * ListPullRow
         * @description A list row in a pull page.
         */
        ListPullRow: {
            row: components["schemas"]["ListRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "lists";
        };
        /**
         * ListRow
         * @description A stored list, as push and pull return it.
         */
        ListRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Server Seq */
            server_seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * MeResponse
         * @description The calling user's public profile.
         */
        MeResponse: {
            /** Clerk User Id */
            clerk_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            storage: components["schemas"]["StorageResponse"];
        };
        /**
         * Mode
         * @description A song's mode.
         * @enum {string}
         */
        Mode: "major" | "minor" | "mixolydian" | "dorian" | "other";
        /**
         * Problem
         * @description An RFC 9457 problem details body, the shape of every error this API returns.
         */
        Problem: {
            /** Detail */
            detail: string;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * Provider
         * @description Where a recording link points.
         * @enum {string}
         */
        Provider: "youtube" | "spotify" | "apple_music" | "bandcamp" | "soundcloud" | "tidal" | "internet_archive" | "other";
        /**
         * PullResponse
         * @description A page of rows changed since the given cursor.
         */
        PullResponse: {
            /** Has More */
            has_more: boolean;
            /** Next Since */
            next_since: number;
            /** Rows */
            rows: (components["schemas"]["SongPullRow"] | components["schemas"]["UserSongPullRow"] | components["schemas"]["ListPullRow"] | components["schemas"]["ListItemPullRow"] | components["schemas"]["RecordingLinkPullRow"] | components["schemas"]["RecordingPullRow"] | components["schemas"]["UserSettingsPullRow"])[];
        };
        /**
         * PushRequest
         * @description A batch of client changes to apply.
         */
        PushRequest: {
            /** Changes */
            changes: components["schemas"]["Change"][];
        };
        /**
         * PushResponse
         * @description One result per change, same order as the request.
         */
        PushResponse: {
            /** Results */
            results: (components["schemas"]["SongChangeResult"] | components["schemas"]["UserSongChangeResult"] | components["schemas"]["ListChangeResult"] | components["schemas"]["ListItemChangeResult"] | components["schemas"]["RecordingLinkChangeResult"] | components["schemas"]["RecordingChangeResult"] | components["schemas"]["UserSettingsChangeResult"])[];
        };
        /**
         * RecordingChangeResult
         * @description The outcome of one change to a recording.
         */
        RecordingChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["RecordingRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "recordings";
        };
        /**
         * RecordingLinkChangeResult
         * @description The outcome of one change to a recording link.
         */
        RecordingLinkChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["RecordingLinkRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "recording_links";
        };
        /**
         * RecordingLinkPullRow
         * @description A recording link row in a pull page.
         */
        RecordingLinkPullRow: {
            row: components["schemas"]["RecordingLinkRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "recording_links";
        };
        /**
         * RecordingLinkRow
         * @description A stored recording link, as push and pull return it.
         */
        RecordingLinkRow: {
            /**
             * Added By User Id
             * Format: uuid
             */
            added_by_user_id: string;
            /** Artwork Url */
            artwork_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label?: string | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            provider: components["schemas"]["Provider"];
            /** Provider Ref */
            provider_ref?: string | null;
            /** Server Seq */
            server_seq: number;
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Title */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * RecordingPullRow
         * @description A recording row in a pull page.
         */
        RecordingPullRow: {
            row: components["schemas"]["RecordingRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "recordings";
        };
        /**
         * RecordingRow
         * @description A stored recording, as push and pull return it. Storage keys stay on the server.
         */
        RecordingRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label?: string | null;
            /** Playback Bytes */
            playback_bytes: number | null;
            /** Playback Mime */
            playback_mime: string | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Server Seq */
            server_seq: number;
            /** Song Id */
            song_id?: string | null;
            source: components["schemas"]["RecordingSource"];
            state: components["schemas"]["RecordingState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * RecordingSource
         * @description How a recording's audio arrived.
         * @enum {string}
         */
        RecordingSource: "microphone" | "upload";
        /**
         * RecordingState
         * @description Where a recording's file is in the upload and transcode pipeline.
         * @enum {string}
         */
        RecordingState: "pending_upload" | "uploaded" | "processing" | "ready" | "failed";
        /**
         * ResolveRequest
         * @description Body of a resolve request: the URL the user just pasted.
         */
        ResolveRequest: {
            /** Url */
            url: string;
        };
        /**
         * ResolveResponse
         * @description Provider, canonical URL, title, and artwork for a resolved link.
         */
        ResolveResponse: {
            /** Artwork Url */
            artwork_url: string | null;
            /** Provider */
            provider: string;
            /** Provider Ref */
            provider_ref: string | null;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /**
         * SignedUrl
         * @description A presigned URL and when it stops working.
         */
        SignedUrl: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Url */
            url: string;
        };
        /**
         * SongChangeResult
         * @description The outcome of one change to a song.
         */
        SongChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["SongRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "songs";
        };
        /**
         * SongPullRow
         * @description A song row in a pull page.
         */
        SongPullRow: {
            row: components["schemas"]["SongRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "songs";
        };
        /**
         * SongRow
         * @description A stored song, as push and pull return it.
         */
        SongRow: {
            /**
             * Alternate Titles
             * @default []
             */
            alternate_titles: string[];
            /** Banjo Tuning */
            banjo_tuning?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Feel */
            feel?: string | null;
            /** Genre */
            genre?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Crooked
             * @default false
             */
            is_crooked: boolean;
            /** Key */
            key?: string | null;
            /** Lyrics */
            lyrics?: string | null;
            mode?: components["schemas"]["Mode"] | null;
            /** Owner User Id */
            owner_user_id: string | null;
            /** Part Structure */
            part_structure?: string | null;
            /** Server Seq */
            server_seq: number;
            time_signature?: components["schemas"]["TimeSignature"] | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Violin Tuning */
            violin_tuning?: string | null;
        };
        /**
         * SongStatus
         * @description Where a player stands with a song.
         * @enum {string}
         */
        SongStatus: "known" | "learning" | "want_to_learn";
        /**
         * StorageResponse
         * @description How much of the recording quota is in use.
         */
        StorageResponse: {
            /** Max File Bytes */
            max_file_bytes: number;
            /** Quota Bytes */
            quota_bytes: number;
            /** Used Bytes */
            used_bytes: number;
        };
        /**
         * TimeSignature
         * @description A song's time signature.
         * @enum {string}
         */
        TimeSignature: "4/4" | "2/4" | "2/2" | "3/4" | "6/8" | "9/8" | "12/8" | "other";
        /**
         * UploadSlotRequest
         * @description What the client is about to upload.
         */
        UploadSlotRequest: {
            /** Bytes */
            bytes: number;
            /** Content Type */
            content_type: string;
        };
        /**
         * UserSettingsChangeResult
         * @description The outcome of one change to a user's settings.
         */
        UserSettingsChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["UserSettingsRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_settings";
        };
        /**
         * UserSettingsPullRow
         * @description A settings row in a pull page.
         */
        UserSettingsPullRow: {
            row: components["schemas"]["UserSettingsRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_settings";
        };
        /**
         * UserSettingsRow
         * @description A stored settings row, as push and pull return it.
         */
        UserSettingsRow: {
            /** @default standard */
            audio_quality: components["schemas"]["AudioQuality"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instruments
             * @default []
             */
            instruments: components["schemas"]["Instrument"][];
            /** Server Seq */
            server_seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * UserSongChangeResult
         * @description The outcome of one change to a user song.
         */
        UserSongChangeResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason?: string | null;
            row?: components["schemas"]["UserSongRow"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_songs";
        };
        /**
         * UserSongPullRow
         * @description A user song row in a pull page.
         */
        UserSongPullRow: {
            row: components["schemas"]["UserSongRow"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            table: "user_songs";
        };
        /**
         * UserSongRow
         * @description A stored user song, as push and pull return it.
         */
        UserSongRow: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Learned From */
            learned_from?: string | null;
            /** Learned On */
            learned_on?: string | null;
            /** Notes */
            notes?: string | null;
            /** Server Seq */
            server_seq: number;
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            status: components["schemas"]["SongStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_v1_links_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    download_v1_recordings__recording_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrl"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    retry_v1_recordings__recording_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    upload_slot_v1_recordings__recording_id__upload_slot_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrl"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    upload_finished_v1_recordings__recording_id__uploaded_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    pull_v1_sync_pull_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    push_v1_sync_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
