// Generated by scripts/vocabulary.mjs from api/openapi.json. Do not edit.
// The API is the source of every value and limit here; see api/src/crosstune/vocabulary.py.

export const AUDIO_QUALITIES = ['low', 'standard', 'high', 'highest'] as const
export type AudioQuality = (typeof AUDIO_QUALITIES)[number]

export const GRANT_SOURCES = ['trial', 'apple', 'stripe', 'comp'] as const
export type GrantSource = (typeof GRANT_SOURCES)[number]

export const INSTRUMENTS = [
  'violin',
  'five_string_banjo',
  'tenor_banjo',
  'guitar',
  'mandolin',
  'bouzouki',
  'mountain_dulcimer',
] as const
export type Instrument = (typeof INSTRUMENTS)[number]

export const MODES = ['major', 'minor', 'mixolydian', 'dorian', 'modal', 'other'] as const
export type Mode = (typeof MODES)[number]

export const PLAY_CONTEXTS = ['row', 'list', 'dock', 'recording_screen'] as const
export type PlayContext = (typeof PLAY_CONTEXTS)[number]

export const PLAY_FIRST = ['recordings', 'apple_music'] as const
export type PlayFirst = (typeof PLAY_FIRST)[number]

export const PROVIDERS = [
  'youtube',
  'spotify',
  'apple_music',
  'bandcamp',
  'soundcloud',
  'tidal',
  'internet_archive',
  'slippery_hill',
  'other',
] as const
export type Provider = (typeof PROVIDERS)[number]

export const RECORDING_ORIGINS = ['own', 'slippery_hill'] as const
export type RecordingOrigin = (typeof RECORDING_ORIGINS)[number]

export const RECORDING_PRECISIONS = ['year', 'month', 'day', 'time'] as const
export type RecordingPrecision = (typeof RECORDING_PRECISIONS)[number]

export const RECORDING_SOURCES = ['microphone', 'upload', 'import'] as const
export type RecordingSource = (typeof RECORDING_SOURCES)[number]

export const RECORDING_STATES = [
  'pending_upload',
  'uploaded',
  'processing',
  'ready',
  'failed',
] as const
export type RecordingState = (typeof RECORDING_STATES)[number]

export const SCAN_STATES = ['pending_upload', 'ready'] as const
export type ScanState = (typeof SCAN_STATES)[number]

export const SCAN_VIEW_CONTEXTS = ['tune', 'row', 'list'] as const
export type ScanViewContext = (typeof SCAN_VIEW_CONTEXTS)[number]

export const SEARCH_STATUSES = ['results', 'unavailable', 'search_only'] as const
export type SearchStatus = (typeof SEARCH_STATUSES)[number]

export const TIME_SIGNATURES = [
  '4/4',
  '2/4',
  '2/2',
  '3/4',
  '3/2',
  '6/8',
  '9/8',
  '12/8',
  'other',
] as const
export type TimeSignature = (typeof TIME_SIGNATURES)[number]

export const STATUSES = ['known', 'learning', 'want_to_learn'] as const
export type TuneStatus = (typeof STATUSES)[number]

export const TUNE_LIMITS = {
  alternate_titles: 200,
  composer: 200,
  genre: 100,
  key: 10,
  lyrics: 20000,
  modes: 4,
  part_structure: 100,
  title: 200,
  tune_type: 100,
  learned_from: 200,
  notes: 20000,
  tuning: 100,
} as const

export const LIST_LIMITS = {
  name: 200,
} as const

export const LINK_LIMITS = {
  artwork_url: 2048,
  provider_ref: 200,
  title: 300,
  url: 2048,
} as const

export const RECORDING_LIMITS = {
  label: 200,
  origin_url: 2048,
} as const

export const LOOP_LIMITS = {
  label: 100,
} as const

export const RECORDING_RANGES = {
  speed_percent: { min: 50, max: 150 },
  pitch_cents: { min: -1200, max: 1200 },
  trim_start_ms: { min: 0 },
} as const

export const LOOP_RANGES = {
  start_ms: { min: 0 },
  color: { min: 0, max: 5 },
} as const
