// Generated by scripts/vocabulary.mjs from src/api/openapi.json. Do not edit.
// The API is the source of every value and limit here; see api/src/crosstune/vocabulary.py.

export const AUDIO_QUALITIES = ['low', 'standard', 'high'] as const
export type AudioQuality = (typeof AUDIO_QUALITIES)[number]

export const INSTRUMENTS = ['violin', 'banjo'] as const
export type Instrument = (typeof INSTRUMENTS)[number]

export const MODES = ['major', 'minor', 'mixolydian', 'dorian', 'modal', 'other'] as const
export type Mode = (typeof MODES)[number]

export const PROVIDERS = [
  'youtube',
  'spotify',
  'apple_music',
  'bandcamp',
  'soundcloud',
  'tidal',
  'internet_archive',
  'other',
] as const
export type Provider = (typeof PROVIDERS)[number]

export const RECORDING_SOURCES = ['microphone', 'upload'] as const
export type RecordingSource = (typeof RECORDING_SOURCES)[number]

export const RECORDING_STATES = [
  'pending_upload',
  'uploaded',
  'processing',
  'ready',
  'failed',
] as const
export type RecordingState = (typeof RECORDING_STATES)[number]

export const STATUSES = ['known', 'learning', 'want_to_learn'] as const
export type SongStatus = (typeof STATUSES)[number]

export const TIME_SIGNATURES = ['4/4', '2/4', '2/2', '3/4', '6/8', '9/8', '12/8', 'other'] as const
export type TimeSignature = (typeof TIME_SIGNATURES)[number]

export const SONG_LIMITS = {
  alternate_titles: 200,
  banjo_tuning: 100,
  feel: 100,
  genre: 100,
  key: 10,
  lyrics: 20000,
  part_structure: 100,
  title: 200,
  violin_tuning: 100,
  learned_from: 200,
  notes: 20000,
} as const

export const LIST_LIMITS = {
  name: 200,
} as const

export const LINK_LIMITS = {
  artwork_url: 2048,
  label: 200,
  provider_ref: 200,
  title: 300,
  url: 2048,
} as const

export const RECORDING_LIMITS = {
  label: 200,
} as const
