#!/usr/bin/env node
// Writes the client's copy of every value and limit the API validates, from the
// committed OpenAPI document. Run by `just contract`; CI fails when the output is stale.
//
//   node scripts/vocabulary.mjs src/api/openapi.json src/api/vocabulary.ts

import { readFileSync, writeFileSync } from 'node:fs'

// Enum schema name -> exported array name. A schema missing here fails the run on
// purpose, so a new list gets a deliberate client name rather than an invented one.
const ARRAY_NAMES = {
  Instrument: 'INSTRUMENTS',
  TuneStatus: 'STATUSES',
  Mode: 'MODES',
  TimeSignature: 'TIME_SIGNATURES',
  Provider: 'PROVIDERS',
  AudioQuality: 'AUDIO_QUALITIES',
  RecordingSource: 'RECORDING_SOURCES',
  RecordingState: 'RECORDING_STATES',
}

// Exported limits object -> the row schemas whose string limits it gathers. A song and
// its user row are one form to the client, so their limits are one object. A row missing
// from the document fails the run, so a renamed schema cannot empty a limits object.
const LIMIT_OBJECTS = {
  SONG_LIMITS: ['TuneRow', 'UserTuneRow', 'InstrumentTuning'],
  LIST_LIMITS: ['ListRow'],
  LINK_LIMITS: ['RecordingLinkRow'],
  RECORDING_LIMITS: ['RecordingRow'],
}

/** A string's max length, directly, under anyOf, or on its array items; else an array's max items. */
function limitOf(property) {
  const candidates = [property, ...(property.anyOf ?? []), property.items ?? {}]
  const text = candidates.find((c) => c.type === 'string' && Number.isInteger(c.maxLength))
  if (text) return text.maxLength
  const list = [property, ...(property.anyOf ?? [])].find(
    (c) => c.type === 'array' && Number.isInteger(c.maxItems),
  )
  return list?.maxItems
}

function quote(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/** @param {{ components?: { schemas?: Record<string, any> } }} doc */
export function render(doc) {
  const schemas = doc.components?.schemas ?? {}
  const lines = [
    '// Generated by scripts/vocabulary.mjs from src/api/openapi.json. Do not edit.',
    '// The API is the source of every value and limit here; see api/src/crosstune/vocabulary.py.',
    '',
  ]
  for (const [name, schema] of Object.entries(schemas)) {
    if (schema.type !== 'string' || !Array.isArray(schema.enum)) continue
    const arrayName = ARRAY_NAMES[name]
    if (!arrayName) throw new Error(`No client name for enum schema ${name}; add it to ARRAY_NAMES`)
    lines.push(
      `export const ${arrayName} = [${schema.enum.map(quote).join(', ')}] as const`,
      `export type ${name} = (typeof ${arrayName})[number]`,
      '',
    )
  }
  for (const [objectName, rows] of Object.entries(LIMIT_OBJECTS)) {
    lines.push(`export const ${objectName} = {`)
    for (const row of rows) {
      const properties = schemas[row]?.properties
      if (!properties)
        throw new Error(`No row schema ${row} for ${objectName}; update LIMIT_OBJECTS`)
      for (const [field, property] of Object.entries(properties)) {
        const limit = limitOf(property)
        if (limit !== undefined) lines.push(`  ${field}: ${limit},`)
      }
    }
    lines.push('} as const', '')
  }
  return lines.join('\n')
}

const [input, output] = process.argv.slice(2)
if (input && output) {
  try {
    writeFileSync(output, render(JSON.parse(readFileSync(input, 'utf8'))))
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}
