// @vitest-environment node
import { spawnSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const SCRIPT = fileURLToPath(new URL('./vocabulary.mjs', import.meta.url))

function generate(schemas: Record<string, unknown>) {
  const dir = mkdtempSync(join(tmpdir(), 'vocabulary-'))
  const input = join(dir, 'openapi.json')
  const output = join(dir, 'vocabulary.ts')
  writeFileSync(input, JSON.stringify({ components: { schemas } }))
  const result = spawnSync(process.execPath, [SCRIPT, input, output], { encoding: 'utf8' })
  return {
    status: result.status,
    stderr: result.stderr,
    text: result.status === 0 ? readFileSync(output, 'utf8') : '',
  }
}

const ROWS = {
  SongRow: {
    properties: {
      title: { type: 'string', maxLength: 200 },
      alternate_titles: { type: 'array', items: { type: 'string', maxLength: 200 } },
      genre: { anyOf: [{ type: 'string', maxLength: 100 }, { type: 'null' }] },
      is_crooked: { type: 'boolean' },
      mode: { anyOf: [{ $ref: '#/components/schemas/Mode' }, { type: 'null' }] },
    },
  },
  UserSongRow: {
    properties: { learned_from: { anyOf: [{ type: 'string', maxLength: 200 }, { type: 'null' }] } },
  },
  ListRow: { properties: { name: { type: 'string', maxLength: 200 } } },
  RecordingLinkRow: { properties: { url: { type: 'string', maxLength: 2048 } } },
  RecordingRow: {
    properties: { label: { anyOf: [{ type: 'string', maxLength: 200 }, { type: 'null' }] } },
  },
}

describe('vocabulary generator', () => {
  it('emits an as-const array and a union type for each known enum, in declaration order', () => {
    const { status, text } = generate({
      ...ROWS,
      Mode: { type: 'string', enum: ['major', 'minor', 'other'] },
    })
    expect(status).toBe(0)
    expect(text).toContain("export const MODES = ['major', 'minor', 'other'] as const")
    expect(text).toContain('export type Mode = (typeof MODES)[number]')
  })

  it('emits one limits object per row, merging song and user song, from direct, nullable, and array item limits', () => {
    const { text } = generate({ ...ROWS, Mode: { type: 'string', enum: ['major'] } })
    expect(text).toContain(
      [
        'export const SONG_LIMITS = {',
        '  title: 200,',
        '  alternate_titles: 200,',
        '  genre: 100,',
        '  learned_from: 200,',
        '} as const',
      ].join('\n'),
    )
    expect(text).toContain('export const LIST_LIMITS = {\n  name: 200,\n} as const')
    expect(text).toContain('export const LINK_LIMITS = {\n  url: 2048,\n} as const')
    expect(text).toContain('export const RECORDING_LIMITS = {\n  label: 200,\n} as const')
    expect(text).not.toContain('is_crooked')
    expect(text).not.toContain('mode:')
  })

  it('fails on an enum the name map does not know', () => {
    const { status, stderr } = generate({ ...ROWS, Flavor: { type: 'string', enum: ['red'] } })
    expect(status).toBe(1)
    expect(stderr).toContain('Flavor')
  })

  it('marks the file as generated', () => {
    const { text } = generate({ ...ROWS, Mode: { type: 'string', enum: ['major'] } })
    expect(text.startsWith('// Generated by scripts/vocabulary.mjs')).toBe(true)
  })
})
