// Generated by Tools/Sources/generate-vocabulary from api/openapi.json. Do not edit.
// The API is the source of every value and limit here; see api/src/crosstune/vocabulary.py.

public enum Vocabulary {
    public static let audioQualities: [String] = ["low", "standard", "high"]
    public static let instruments: [String] = [
        "violin", "five_string_banjo", "tenor_banjo", "guitar", "mandolin", "bouzouki", "mountain_dulcimer",
    ]
    public static let modes: [String] = ["major", "minor", "mixolydian", "dorian", "modal", "other"]
    public static let providers: [String] = [
        "youtube", "spotify", "apple_music", "bandcamp", "soundcloud", "tidal", "internet_archive", "other",
    ]
    public static let recordingSources: [String] = ["microphone", "upload"]
    public static let recordingStates: [String] = ["pending_upload", "uploaded", "processing", "ready", "failed"]
    public static let timeSignatures: [String] = ["4/4", "2/4", "2/2", "3/4", "3/2", "6/8", "9/8", "12/8", "other"]
    public static let statuses: [String] = ["known", "learning", "want_to_learn"]

    public enum Limits {
        public enum Tune {
            public static let alternateTitles = 200
            public static let composer = 200
            public static let genre = 100
            public static let key = 10
            public static let learnedFrom = 200
            public static let lyrics = 20000
            public static let modes = 4
            public static let notes = 20000
            public static let partStructure = 100
            public static let title = 200
            public static let tuneType = 100
            public static let tuning = 100
        }
        public enum List {
            public static let name = 200
        }
        public enum Link {
            public static let artworkUrl = 2048
            public static let label = 200
            public static let providerRef = 200
            public static let title = 300
            public static let url = 2048
        }
        public enum Recording {
            public static let label = 200
        }
    }
}
