/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordRouteImport } from './routes/record'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as ListsIdRouteImport } from './routes/lists.$id'
import { Route as SongsIdRouteImport } from './routes/songs.$id'
import { Route as SongsNewRouteImport } from './routes/songs.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIdRoute = SongsIdRouteImport.update({
  id: '/songs/$id',
  path: '/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsNewRoute = SongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/record': typeof RecordRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/lists/$id': typeof ListsIdRoute
  '/songs/$id': typeof SongsIdRoute
  '/songs/new': typeof SongsNewRoute
  '/lists/': typeof ListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/record': typeof RecordRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/lists/$id': typeof ListsIdRoute
  '/songs/$id': typeof SongsIdRoute
  '/songs/new': typeof SongsNewRoute
  '/lists': typeof ListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/record': typeof RecordRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/lists/$id': typeof ListsIdRoute
  '/songs/$id': typeof SongsIdRoute
  '/songs/new': typeof SongsNewRoute
  '/lists/': typeof ListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/record'
    | '/recordings'
    | '/settings'
    | '/lists/$id'
    | '/songs/$id'
    | '/songs/new'
    | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/record'
    | '/recordings'
    | '/settings'
    | '/lists/$id'
    | '/songs/$id'
    | '/songs/new'
    | '/lists'
  id:
    | '__root__'
    | '/'
    | '/record'
    | '/recordings'
    | '/settings'
    | '/lists/$id'
    | '/songs/$id'
    | '/songs/new'
    | '/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordRoute: typeof RecordRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  ListsIdRoute: typeof ListsIdRoute
  SongsIdRoute: typeof SongsIdRoute
  SongsNewRoute: typeof SongsNewRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$id': {
      id: '/songs/$id'
      path: '/songs/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof SongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/new': {
      id: '/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof SongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordRoute: RecordRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  ListsIdRoute: ListsIdRoute,
  SongsIdRoute: SongsIdRoute,
  SongsNewRoute: SongsNewRoute,
  ListsIndexRoute: ListsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
