export const NEW_RECORDING = 'New recording'
export const DISCARD_TITLE = 'Discard this recording?'
export const NOT_RECORDING = 'Not recording'
export const STARTING_MICROPHONE = 'Starting the microphone'
export const INTERRUPTED = 'Interrupted'
export const SAVING = 'Saving'
export const SAVED = 'Saved'
export const NOT_SAVED_MESSAGE = 'The recording is not saved.'
export const DISCARD = 'Discard'
export const STOP = 'Stop'
export const DONE = 'Done'
export const INTERRUPTED_MESSAGE =
  'Recording interrupted. The phone locked or another app took the microphone. Stop to keep what you have, or wait for it to resume.'
export const FILING_UNDER = 'Filing under'
